language: perl
dist: trusty
sudo: required
branches:
  only:
  - master
before_install: make -f Makefile.travis install
script: make -f Makefile.travis test
after_success: make -f Makefile.travis after_success
deploy: 
  - make -f Makefile.travis deploy-doc
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: heHbYckMgQLcTR/Pa8ypaA6VEqfurnpLfGVWvlFDhtmNO5UTqs80l1yRF4E2iHyqfCfS6nYhPaSrUFq+z1LsjGFdQXfJ0hSnB9zI0/BcoBU7COHZZRyUC8XXCQRVML+Yygp0fLCi/MVx5ncahQCcQkqWkHqHpjDEpYK18UHRBK6Y/ycf7Io2amVlS4YrJ/kloAI0TexRBPmG65+A1ReMSigScIXB2OalQ3y+6fziEkyg+2YMcTpnfM6aDH7LPajd4VxyyFaTJzrVMC/MEE3FuCD5Tvd806b5DREPb6/EMdWgRio8D8jfqdtmGuPfl3ykyLKp3+AFwU+Itb5n+J4bJPDM8KR0M7NGedGZFfnibBLhh62aTHSxhiA3M7IEWx8+dL1fTEuGvbktib3Cl8JQQjjXNAV7aVphRPqkipEx7O++YLMNH0IEaaDaETpFSYLdl22J6UIKAARH6kwCegFKfcd6cGzF+d+RISgYE0P7nw/delxVKQHG8ZIlowbysjLMZ/FDGEjrnMMWC/B95FIiijcW9hNICzWBCDY82BXW3AJtErDwBpMdfU2yEhk7A/pLpMYJEZ27aCSJbnjgYwAHtazTZXhsXUNEF5HMoEQHW5wgLYLk3XGYTSNBotb48cWCHvbnDWi5fhcns5vEHU4/ham9OcG/TunkdSUUE94gAiI=
  - secure: ga2+r3OUUw+rJ+LSiiQh/o1GyDp87qbLAzx2wWtzqOmHDnMDjRvNBodlBiZoEsnAIGe6iBHt0ItoI002hk0v51515TC0cA8XzWO/+WDDu0nSToUh5lYmiEav9dkx1Sb8RtSbQiofMlQ+DJzb70V4gYXhH2nb0FlhWFhLoWr2J0H0RFb6/keyMwQlN8hXQ0id+YtK+HzMf07ASAaVbnLxJfbbSOnhvKHVLBtG3DcCHolFJbg1BR5zbN3FXU97VeviOVphAEUcIPj57MCs8Ez0p5ahcw3MBjxj0jWujAGnWAx+9wFldjGStOWzsvzGn4dxU4U1yYyknf2KyP1+RxTUbDfvVBM3tqraD9lh9WMzg8w+jkNsWe9I+XnnWawrJqIgrWQ34bYRa9Pp1PNoSR+Ld1z0iDWkzWL9XmZ6fAHTCbXvp/o7Hy7ZSB94ZrDycTMGN5SiqyzQHdZLCq0SMino6Q2H2Mu2fiIWnJM4ly/MZxEIs6Z1UJ+ibv8HMkRJLW0g8mCgdnNGMKEQZgBrWPH1CaQHFTx8BPP6mz1flq0TG0p5xN7YYuse5mbRIYR4+zEx9mG6YnIJXMRUK/4Sx4j1Zl81ZPPc8zv8TxlKSm8IQ/Hso2JDqFyCKkDh6dHgFsw0vmr03zpTgs4+pmIpThWjRM/MeWmGdw89uTDYmAq4OuQ=
